Used for scientific computing

<b> </b>

NumPy is the library that gives Python its ability to work with data at speed. 
<b></b>

useful linear algebra, Fourier transform, and random number capabilities
<b></b>

Originally, launched in 1995 as ‘Numeric,’ NumPy is the foundation on which many important Python data science libraries are built, including Pandas, SciPy and scikit-learn.

In [0]:
import numpy as np

Creating **Arrays**

In [2]:
np.array([1,2,3]) #one dimensional

array([1, 2, 3])

In [3]:
np.array([(1,2,3),(4,5,6)]) #Two dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
my_list = [1,2,3,4]

In [5]:
np.array(my_list)

array([1, 2, 3, 4])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.linspace(0,10,3) 

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,100,12)

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [11]:
np.arange(0,10,3) 

array([0, 3, 6, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.random.rand(2)

array([0.93114597, 0.92870315])

In [14]:
np.random.rand(4,5)

array([[0.09268667, 0.71134892, 0.74447848, 0.99379431, 0.32065647],
       [0.84150704, 0.790254  , 0.17260027, 0.86244008, 0.52621532],
       [0.92388753, 0.07492731, 0.93257584, 0.88670068, 0.44799747],
       [0.7317299 , 0.85026448, 0.43541306, 0.72409257, 0.30177437]])

**Creating a Matrix**

In [0]:
list_mat = ([1,2,3],[4,5,6],[7,8,9])

In [16]:
np.array(list_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
ar = np.arange(1,10,1)

In [18]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Min and Max

In [0]:
ar = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [21]:
ar

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [22]:
ar.min()

2

In [23]:
ar.max()

49

In [24]:
ar.argmax()

4

In [25]:
ar.argmin()

5

Shape

In [26]:
ar.shape

(10,)

find dtype

In [27]:
ar.dtype

dtype('int64')

In [0]:
ar1 = np.array([1.2,3.4,4.5])

In [29]:
ar1.dtype

dtype('float64')

**Adding/removing Elements**

In [0]:
ar = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [31]:
np.append(ar,[1,2])

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39,  1,  2])

In [32]:
np.insert(ar,2,[3,4])   #inserts [3,4] before index 2

array([10, 12,  3,  4, 41, 17, 49,  2, 46,  3, 19, 39])

In [33]:
np.delete(ar,3) #delete index 3

array([10, 12, 41, 49,  2, 46,  3, 19, 39])

Combining/splitting

In [0]:
arr = [1,2,3]
arr1 = [4,5,6]

In [35]:
np.concatenate((arr,arr1))

array([1, 2, 3, 4, 5, 6])

In [36]:
ar

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [37]:
np.split(ar,2) 

[array([10, 12, 41, 17, 49]), array([ 2, 46,  3, 19, 39])]

Indexing/Slicing

In [0]:
ar = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [39]:
ar[4]

49

In [40]:
ar[[3,5]]

array([17,  2])

In [0]:
ar[0] = 1

In [42]:
ar

array([ 1, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [43]:
ar[0:3]

array([ 1, 12, 41])

In [44]:
ar[3:5]

array([17, 49])

In [45]:
ar[:2]

array([ 1, 12])

In [46]:
ar[5:]

array([ 2, 46,  3, 19, 39])

In [47]:
ar < 20

array([ True,  True, False,  True, False,  True, False,  True,  True,
       False])

In [48]:
ar[ar < 5]

array([1, 2, 3])

In [49]:
(ar < 5) | (ar > 30)

array([ True, False,  True, False,  True,  True,  True,  True, False,
        True])

In [50]:
ar[(ar < 5) | (ar > 30)]

array([ 1, 41, 49,  2, 46,  3, 39])

In [51]:
~ar

array([ -2, -13, -42, -18, -50,  -3, -47,  -4, -20, -40])

In [0]:
my_list = ([10,2,39],[14,87,62],[70,18,49])

In [0]:
ar = np.array(my_list)

In [54]:
ar

array([[10,  2, 39],
       [14, 87, 62],
       [70, 18, 49]])

In [55]:
ar[:,:1]

array([[10],
       [14],
       [70]])

In [56]:
ar[:1]

array([[10,  2, 39]])

In [57]:
ar[2:]

array([[70, 18, 49]])

In [58]:
ar[:2,:2]

array([[10,  2],
       [14, 87]])

In [59]:
ar[1:,1:]

array([[87, 62],
       [18, 49]])

In [0]:
ar[0,0] = 1

In [61]:
ar

array([[ 1,  2, 39],
       [14, 87, 62],
       [70, 18, 49]])

In [62]:
ar > 5 

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [63]:
ar[ar > 5]

array([39, 14, 87, 62, 70, 18, 49])

In [64]:
~ar

array([[ -2,  -3, -40],
       [-15, -88, -63],
       [-71, -19, -50]])

Copying/sorting/reshaping

In [0]:
ar = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [0]:
ar1 = ar.copy()

In [0]:
ar1.sort()

In [68]:
ar1

array([ 2,  3, 10, 12, 17, 19, 39, 41, 46, 49])

In [69]:
ar

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

2D array

In [0]:
my_list = ([10,2,39],[14,87,62],[70,18,49])

In [0]:
ar = np.array(my_list)

In [72]:
ar

array([[10,  2, 39],
       [14, 87, 62],
       [70, 18, 49]])

In [0]:
ar1 = ar.copy()

In [0]:
ar1.sort()

In [75]:
ar1

array([[ 2, 10, 39],
       [14, 62, 87],
       [18, 49, 70]])

In [76]:
ar

array([[10,  2, 39],
       [14, 87, 62],
       [70, 18, 49]])

In [77]:
ar1.T

array([[ 2, 14, 18],
       [10, 62, 49],
       [39, 87, 70]])

Math operations

In [0]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

In [79]:
np.add(ar,10)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
np.subtract(ar,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.multiply(ar,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [82]:
np.divide(ar,-1)

array([ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.])

In [83]:
np.power(ar,2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [0]:
ar = np.array([1,2,3])
ar1 = np.array([4,5,6])

In [85]:
np.add(ar,ar1)

array([5, 7, 9])

In [86]:
np.subtract(ar1,ar)

array([3, 3, 3])

In [87]:
np.multiply(ar,ar1)

array([ 4, 10, 18])

In [88]:
np.divide(ar1,ar)

array([4. , 2.5, 2. ])

In [89]:
np.power(ar1,ar)

array([  4,  25, 216])

In [90]:
np.array_equal(ar,ar1)

False

In [0]:
ar = np.array([4,9,16])

In [92]:
np.sqrt(ar)

array([2., 3., 4.])

In [93]:
np.sin(ar)

array([-0.7568025 ,  0.41211849, -0.28790332])

In [94]:
np.log(ar)

array([1.38629436, 2.19722458, 2.77258872])

In [95]:
np.abs(ar)


array([ 4,  9, 16])

In [0]:
ar = np.array([1.2,3.7,5.4,6.8])

In [97]:
np.ceil(ar)

array([2., 4., 6., 7.])

In [98]:
np.floor(ar)

array([1., 3., 5., 6.])

In [99]:
np.round(ar)

array([1., 4., 5., 7.])

Statistics


In [0]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

In [101]:
np.mean(ar)

5.5

In [102]:
ar.sum()

55

In [103]:
ar.min()

1

In [104]:
ar.max()

10

In [105]:
np.var(ar)

8.25

In [107]:
np.std(ar)

2.8722813232690143

In [0]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

In [0]:
ar1 = np.where(ar>5, ar*100,ar)

In [121]:
ar1

array([   1,    2,    3,    4,    5,  600,  700,  800,  900, 1000])

In [0]:
my_list = [1,2,3],[4,5,6]

In [0]:
ar = np.array(my_list)

In [124]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
ar1 = np.where(ar>3, ar*100,ar)

In [126]:
ar1

array([[  1,   2,   3],
       [400, 500, 600]])