In [2]:
25*4

100

In [3]:
(5000*10*4)/100

2000.0

In [4]:
4**2

16

In [5]:
(1 + 2 ** 3 // 4 * 5)

11

In [ ]:
my_int = 20

In [ ]:
my_float = 15.85

In [ ]:
my_string = 'Hello World'

In [ ]:
my_bool = True

In [ ]:
bank_balance = 200

In [ ]:
print(bank_balance)

In [ ]:
height = 50
width = 40
area_of_rectangle= height * width
print(area_of_rectangle)

In [ ]:
height = 60
width = 40
new_area_of_rectangle = height * width
print(new_area_of_rectangle)

In [ ]:
height = 1.7

In [ ]:
weight = 72.25
bmi = int(weight / (height * height))
print(bmi)

In [ ]:
gender = "male"
is_obese = False

In [ ]:
"game" + 1

In [ ]:
total_interest = 9762.69

In [ ]:
type(total_interest)

In [ ]:
bmi = 25

In [ ]:
bmi=25
bmi_str=str(bmi)
message="BMI is"+" "+bmi_str
print(message)

In [ ]:
first="Cloudx"
second="Lab"
final=first+second
print(final)

In [ ]:
animal = "cat"

In [ ]:
ten_animals = animal * 10

In [ ]:
ten_animals

In [ ]:
height=20
width=80
area_of_rectangle=height*width
print(area_of_rectangle)

In [ ]:
area_of_circle = 78.5

In [ ]:
area_of_circle = str(area_of_circle)

In [ ]:
area_of_circle_msg = "Area of the circle is - " + area_of_circle
print(area_of_circle_msg)

In [ ]:
square_area = 8.9**2

In [ ]:
square_area_type = type(square_area)

In [ ]:
square_area_int = int(square_area)

In [ ]:
square_area_str = str(square_area_int)

In [ ]:

def get_name():
    print("Cloudxlab")

In [ ]:
get_name()

In [ ]:
def my_function(number):
    xyz = number
    xyz_str = str(number) + "cloudxlab"
    print(xyz_str)
    

In [ ]:
my_function(10)

In [ ]:
import math
def new_function(num):
    return math.pi*num

def void_function(num1,num2):
    print(new_function(num1**num2))
    


In [ ]:
void_function(4.6,7.3)

In [ ]:
def input_name():
    print('What am I studying?')
    return input()

In [ ]:
subject = input_name()

In [ ]:
print(subject)

In [ ]:
def bool_func(num1,num2,num3,num4):
    exp1=str(num1>num2)
    exp2=str(num1==num3)
    exp3=str(num2<=num3)
    exp4=str(num4!=num1)
    return exp1+exp2+exp3+exp4

bool_func(1,2,3,4)

In [ ]:
def conditional_statements(num1, num2, num3, num4):

    if num1 < num2 and num1 > num3 and num1 == num4 and num3 < num2 and num3 < num4 and type(num2) == float and type(num1) == int and type(num3) == int and type(num4) == int:

        return(num1+num2+num3+num4)

    else:

        return None

print(conditional_statements(4,5.5,1,4))

In [ ]:
def except_func(num):

    try:
        return float(num)*float(num)

    except:
        return'invalid number'

num=input('enter number')
res=except_func(num)
print(res)

In [ ]:
def print_even(n):
    if n!=0:
        for i in range(0,n):
            if i%2==0:
                print(i)
            else:
                continue
    else:
        print(end="")

In [ ]:
def compound_interest(principle, rate, time):
    if principle>0 and rate>0 and time>0:
        comp_interest = principle * (pow((1 + rate / 100), time)) - principle
    else:
        comp_interest = 0
    return comp_interest

In [ ]:
def sum_func(a):
    if type(a)!=int or a<0:
        return -1
    if type(a)==int and a>=0:
        return sum(range(0,(a+1)))

In [ ]:
def special_func(num):
    if type(num) is int and num > 0:
        sum = 1 # 1 is always a factor 
        i = 3 # because 2 will be a even facotor
        while i <= num:
            if num%i == 0 and i%2 != 0:
                sum = sum + i
            i = i + 1
        return sum
    else:
        return -10

In [ ]:
def str_func(arg):
    return arg[-1]

def sum_str_func(arg1):
    n = [int(x) for x in str(arg1)]
    result = sum(n)
    return result

In [ ]:
def slicing_func(str):
    print(str[2:])
    

In [ ]:

slicing_func("Hello World")

In [ ]:
a = "cloudxlab"
a[1] = 'm'

In [ ]:
a = "Cloudxlab is a large ed-tech platform for ml and big data"
count = 0
for letter in a:
     if letter == 'l':
        count = count + 1

In [ ]:
count

In [ ]:
result = 'cloud' in 'cloudxlab'
print (result)

In [ ]:
string = "machine"
print (string == " machine")

In [ ]:
a = "cloudxlab"
dir(a)

In [ ]:
help(str.translate)


In [ ]:
print(a.upper())

In [ ]:
print(a)

In [ ]:
def email_func(mail):
    a=mail.find('@')
    if a>-1:
        b=mail.find(" ",a)
        c=mail[0:b].split()
        d=c[-1]
        print(d)
    else:
        return None

In [ ]:
print('%d+3' % 3)

In [ ]:
print("%f %f %s")

In [ ]:
print("%f %s %d" % (12.3, 12, 'cloudxlab')

In [ ]:
a = [1,2,3,4,5,6,7,8,9]
a[2:5] = [7,4,9]

In [ ]:
sum(a)

In [ ]:
a = [23,12,32,1,2,34,56]
a.append(12)
print(a[len(a)-2])

In [ ]:
a.extend(a)

In [ ]:
sum(a)

In [ ]:
a.sort()
print(a[2] + a[7])

In [ ]:
list = [12,23,43,[2,4,5], 2, 4,5]
list.pop(3)

In [ ]:
sum(list)

In [ ]:
list = ['cloudx', 'lab', 'provides', 'cloud', 'lab']
del list[:]

In [ ]:
len(list)

In [ ]:

def str_list_func(str):
    ret_str = []
    str1 = str.split()
    for word in str1:
        if len(word) > 1:
            word = word[-1] + word[1:-1] + word[0]
            ret_str.append(word)
        else:
            ret_str.append(word)
    return ' '.join(ret_str)    

In [ ]:
str_list_func("I am the gold")

In [ ]:
def file_read_func(arg):
    try:
        a=open(arg)
        s=""
        for line in a:
            s=s+line
            s=s.replace("\n"," ")
            s=s.replace(" ","")
            list(s)
            c=len(s)
            return sum(c)
    except:
        return -1


In [ ]:
def file_read_func(path):
    try:
        with open(path) as f:
            s = 0
            str1 = f.read()
            str1 = str1.replace('\n', '')
            str1 = str1.replace(" ", '')
            return len(str1)
    except :
        return -1

In [ ]:
file_read_func("/cxldata/python_sample_file")

In [ ]:
check = 0
with open("/cxldata/python_sample_file") as f:
    for line in f:
        if(line.startswith('w')):
            check = check + 1

In [ ]:
check

In [ ]:
with open("python_file_writing.txt", 'w') as f:
    f.write("I am learning Python at CloudxLab.")

In [ ]:
d = { 'one' : 1 , 'two' : 2, 'three' : 3, 'four': 4 }

In [ ]:
d = { 'one' : 1 , 'two' : 2, 'three' : 3, 'four': 4 }
print(len(d))

In [ ]:
print('three' in d)

In [ ]:
print(4 in d)

In [ ]:
print(5 in d and 2 in d)

In [ ]:
def dict_func(arg_Str):
    words = arg_Str.split()
    word_count_dict = {}
    for word in words:
        word_count_dict[word] = word_count_dict.get(word,0) + 1
    return word_count_dict
print(dict_func('one two two three three three four four four four'))
print(dict_func("How many wood chucks chuck wood if all wood chuck wood"))

In [ ]:
t = (12,323, 'd', [1,23], False)

In [ ]:
t = (1)
type(t)

In [ ]:
t = tuple()
print(t)

In [ ]:
t1 = tuple("1,2,3,4,5")
t2 = tuple([1,2,3,4,5])
t3 = tuple((1,2,3,4,5))

In [ ]:
len(t3)

In [ ]:
t = (1,3,5,2,54,34,2,34,5)
l = len(t)
print(t[l-2])

In [ ]:
t2 = t[2:5]

In [ ]:
t2


In [ ]:
t3 = t[1:3] + t2[:]

In [ ]:
t3

In [ ]:
print((0, 1, 2) < (0, 3, 4))

In [ ]:
l = [(0,23,34), (2,34,23), (1,34,23)]
l.sort()

In [ ]:
l[2]

In [ ]:
2+34+23

In [ ]:
import numpy as np
def dict_tuple_func(assume):
    d={}
    b=0
    c=set(assume)
    for i in assume:
        if(d.get(i)):
            d[i]=d[i]+1
        else:
            d[i]=1
    for j in c:
        b=b+j

    return d,b

In [ ]:

dict_tuple_func([1,1])

In [ ]:
import re

hand = open()



In [ ]:
!pwd

In [ ]:
!head -n 15 /cxldata/datasets/project/mbox-short.txt

In [ ]:
def number_of_lines():
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    read = fhand.readlines()
    count = len(read)
    print(count)
    return count

In [ ]:

number_of_lines()

In [ ]:
def count_number_of_lines():
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    count = 0
    for line in fhand:
        line = line.rstrip()
        if line.startswith('Subject:'):
            count = count + 1
    return count

In [ ]:
count_number_of_lines()

In [ ]:
def average_spam_confidence():
    list = []
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    for line in fhand:
        line = line.rstrip()
        if line.startswith('X-DSPAM-Confidence:'):
            list.append(float(line.split(':')[1]))
    return(sum(list)/len(list))

In [ ]:

average_spam_confidence()

In [ ]:
def find_email_sent_days():
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    for line in fhand:
        line = line.rstrip()
        if line.startswith('From'):
            print(line.split(' '))
            if len(line) > 2 :
                

In [ ]:
find_email_sent_days()

In [ ]:
def find_email_sent_days():
    daysdict={}
    dayslist=[]
    fhand=open('/cxldata/datasets/project/mbox-short.txt')
    for line in fhand:
        dayslist=line.split()
        if len(dayslist)>3 and line.startswith('From'):
            day=dayslist[2]
            if day not in daysdict:
                daysdict[day]=1
            else:
                daysdict[day]+=1
    return daysdict

In [ ]:
find_email_sent_days()

In [ ]:
def count_message_from_email():
    emaildict={}
    fhand=open('/cxldata/datasets/project/mbox-short.txt')
    for line in fhand:
        line = line.rstrip()
        if line.startswith('From:'):
            email = line.split(' ')[1]
            print(email)
            if email not in emaildict:
                emaildict[email] = 1
            else:
                emaildict[email]+=1
    return emaildict

In [ ]:
count_message_from_email()

In [ ]:
import re
def count_message_from_domain():
    emaildict = {}
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    for line in fhand:
        line = line.rstrip()
        if line.startswith('From:'):
            email = line.split(' ')[1]
            email_1 = email.split('@')[1]
            if email_1 not in emaildict:
                emaildict[email_1] = 1
            else:
                emaildict[email_1]+=1
    return emaildict

In [ ]:
count_message_from_domain()

In [ ]:
import numpy as np

In [ ]:
list = [1,2,3]

In [ ]:
list_array = np.array(list)

In [ ]:
tup = (1,2,3)

In [ ]:
my_tup_array = np.array(tup)

In [ ]:
tup_dim = (3, 4)

In [ ]:
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
print(my_zeros_array)

In [ ]:
my_ones_array = np.ones(tup_dim, dtype=np.int16)
print(my_ones_array)

In [ ]:
my_seven_array = np.full(tup_dim,7, dtype=np.int16)

In [ ]:
my_seven_array

In [ ]:
my_identity_array = np.identity(4, dtype=np.float64)
print(my_identity_array)

In [ ]:
my_rand_array = np.random.rand(3,4)

In [ ]:
my_uninitialized_array = np.empty(tup_dim)

In [ ]:
my_range_array = np.arange(10,30,5)

In [ ]:
my_range_array

In [ ]:
my_spaced_array = np.linspace(0,5/3,6)

In [ ]:
my_spaced_array

In [ ]:
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

In [ ]:
my_array

In [ ]:
dim(my_array)

In [ ]:
import numpy as np
import os

In [6]:
import pandas as pd
# defining housing.csv file path
HOUSING_PATH = '../ml/machine_learning/datasets/housing/'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [9]:
FILE = 'housing_short.csv'

In [22]:
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

In [25]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [26]:
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [2]:
import numpy as np
my_first_arr = np.array([1,2,3,4,5,6,7,8])

In [3]:
my_new_arr = my_first_arr.reshape(2,4)

In [4]:
print(my_new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
print(my_first_arr)

[1 2 3 4 5 6 7 8]


In [6]:
my_second_arr = np.array([0,1,2,3,4,5,6,7,8])

In [8]:
my_updated_arr = my_second_arr.reshape(3,3)

In [9]:
print(my_updated_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [1]:
import numpy as np
from sklearn.datasets import load_sample_image

In [2]:
china = load_sample_image("china.jpg")

In [4]:
china.shape


(427, 640, 3)

In [5]:
image = china[150:220, 130:250]

In [6]:
image.shape

(70, 120, 3)

In [7]:
height, width, channels = image.shape

In [8]:
image_grayscale = image.mean(axis=2).astype(np.float32)

In [9]:
image_grayscale.shape

(70, 120)

In [10]:
images = image_grayscale.reshape(1, height, width, 1)

In [11]:
images.shape

(1, 70, 120, 1)

In [18]:
images

array([[[[ 50.333332],
         [ 98.333336],
         [ 98.666664],
         ...,
         [ 90.      ],
         [ 57.      ],
         [ 99.333336]],

        [[ 56.333332],
         [108.333336],
         [ 96.      ],
         ...,
         [ 90.666664],
         [ 66.333336],
         [ 68.666664]],

        [[ 47.666668],
         [116.666664],
         [105.666664],
         ...,
         [ 94.      ],
         [ 65.333336],
         [ 64.333336]],

        ...,

        [[ 20.333334],
         [ 18.666666],
         [ 17.666666],
         ...,
         [ 19.      ],
         [ 22.333334],
         [ 21.333334]],

        [[ 14.666667],
         [ 19.333334],
         [ 20.      ],
         ...,
         [ 15.      ],
         [ 18.666666],
         [ 18.333334]],

        [[ 16.      ],
         [ 15.666667],
         [ 24.      ],
         ...,
         [ 20.333334],
         [ 14.      ],
         [ 17.666666]]]], dtype=float32)

In [4]:
import numpy as np
my_orig_arr = np.array([1, 15, 3, 9, 26, 7, 89, 12])

In [5]:
my_rev_arr = my_orig_arr[ : : -1]

In [6]:
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [8]:
apple = np.array([1, 8, 23, 3, 18, 91, 7, 15])

In [10]:
apple_slice = apple[1 : 4]

In [11]:
print(apple_slice)

[ 8 23  3]


In [12]:
apple_slice[1] = 99999

In [13]:
print(apple_slice)

[    8 99999     3]


In [14]:
print(apple)

[    1     8 99999     3    18    91     7    15]


In [15]:
apple_slice_new = apple[2 : 5].copy()

In [16]:
apple_slice_new[1] = 222222

In [17]:
print(apple_slice_new)

[ 99999 222222     18]


In [18]:
print(apple)

[    1     8 99999     3    18    91     7    15]


In [28]:
import numpy as np
from sklearn.datasets import load_sample_image

In [29]:
china = load_sample_image("china.jpg")

In [30]:
portion = china[120:250,110:230]

In [31]:
print(portion.shape)

(130, 120, 3)


In [36]:
my_multi_arr = np.arange(20).reshape(4,5)

In [37]:
my_multi_arr_portion = my_multi_arr[2:4,2:5]

In [38]:
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [44]:
my_2d_arr = np.arange(20).reshape(4,5)

In [45]:
my_1d_arr = my_2d_arr.ravel()

In [46]:
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [54]:
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)

In [55]:
c_arr = a_arr  + b_arr

In [56]:
print(c_arr)

[60 71 82 93]


In [58]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)

In [59]:
f_arr = d_arr  - e_arr

In [60]:
print(f_arr)

[60 69 78 87]


In [77]:
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )

In [78]:
M_arr = A_arr * B_arr

In [79]:
print(M_arr)

[[10 72]
 [ 4 42]]


In [80]:
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )

In [81]:
P_arr = np.dot(C_arr,D_arr)

In [82]:
print(P_arr)

[[19 94]
 [15 74]]


In [99]:
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array( [ [2, 10], [4, 5] ] )

In [100]:
T_div = R_div/S_div

In [101]:
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [102]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array( [ [2, 10], [8, 3] ] )


In [143]:
T_int_div = R_int_div//S_int_div

In [144]:
print(T_int_div)

[[12  6]
 [ 5 23]]


In [105]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array( [ [2, 10], [8, 3] ] )

In [106]:
T_mod = R_mod % S_mod

In [107]:
print(T_mod)

[[0 5]
 [0 1]]


In [163]:
R_exp= np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )

In [164]:
T_exp = R_exp**S_exp

In [165]:
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [174]:
U = np.array([ [ 22, 45], [90, 4 ] ] )

In [176]:
print(U<45)

[[ True False]
 [False  True]]


In [182]:
X_stat = np.array([ [ 1, 2, 3], [ 4, -5, 6] ])

In [183]:
print("mean = ", X_stat.mean())

mean =  1.8333333333333333


In [184]:
print("Variance = ", X_stat.var())

Variance =  11.805555555555557


In [185]:
print("Standard Deviation = ", X_stat.std())

Standard Deviation =  3.435921354681384


In [186]:
print("min = ", X_stat.min())

min =  -5


In [187]:
print("max = ", X_stat.max())

max =  6


In [188]:
print("sum = ", X_stat.sum())

sum =  11


In [189]:
print("product = ", X_stat.prod())

product =  -720


In [211]:
Z = np.arange(18).reshape(2,3,3)

In [212]:
print(Z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [213]:
print(Z.sum(axis =2))

[[ 3 12 21]
 [30 39 48]]


In [221]:
N = np.arange(6).reshape(3,2)

In [222]:
print(N)

[[0 1]
 [2 3]
 [4 5]]


In [223]:
print("Transpose = ",N.T)

Transpose =  [[0 2 4]
 [1 3 5]]


In [230]:
X_broad = np.ones(9).reshape(3,3)

In [231]:
print(X_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [233]:
Y_broad = np.arange(3)

In [234]:
print(Y_broad)

[0 1 2]


In [235]:
Z_broad = X_broad + Y_broad

In [236]:
print(Z_broad)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [2]:
import pandas as pd

In [3]:
mydf = pd.read_csv('../ml/machine_learning/datasets/housing/housing.csv',index_col = 0)

In [5]:
mydf.describe()

latitude  housing_median_age   total_rooms  total_bedrooms  \
count  20640.000000        20640.000000  20640.000000    20433.000000   
mean      35.631861           28.639486   2635.763081      537.870553   
std        2.135952           12.585558   2181.615252      421.385070   
min       32.540000            1.000000      2.000000        1.000000   
25%       33.930000           18.000000   1447.750000      296.000000   
50%       34.260000           29.000000   2127.000000      435.000000   
75%       37.710000           37.000000   3148.000000      647.000000   
max       41.950000           52.000000  39320.000000     6445.000000   

         population    households  median_income  median_house_value  
count  20640.000000  20640.000000   20640.000000        20640.000000  
mean    1425.476744    499.539680       3.870671       206855.816909  
std     1132.462122    382.329753       1.899822       115395.615874  
min        3.000000      1.000000       0.499900        14999.000000  
25%      787.000000    280.000000       2.563400       119600.000000  
50%     1166.000000    409.000000       3.534800       179700.000000  
75%     1725.000000    605.000000       4.743250       264725.000000  
max    35682.000000   6082.000000      15.000100       500001.000000